#!/usr/bin/env bash
# Script that transfers a file from our client to a server

# Assigns parameters to variables
FILE=$1
SERVER_IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

# Transfers the file with strict host key checking disabled
if [ "$PATH_TO_SSH_KEY" ]; then
	scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$SERVER_IP:~/"
elif [ "$USERNAME" ]; then
	scp -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$SERVER_IP:~/"
else
	# If there is less than 3 parameters passed
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi
