#!/usr/bin/env bash
# Script that transfers a file from our client to a server

# Checks if less than 3 parameters passed
if [ $# -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# Assigns parameters to variables
file=$1
ip=$2
username=$3
sshpath=$4

# Transfers the file with strict host key checking disabled
scp -i "$sshpath" -o StrictHostKeyChecking=no "$file" "$username@$ip:~/"
