#!/usr/bin/env bash
# Script that installs Nginx

# Update package list
sudo apt-get update -y

# Install Nginx
sudo apt install nginx -y

# Return a page that contains the string "Hello World!"
echo "Hello World!" | sudo tee /etc/nginx/html/index.html

# Restart Nginx
sudo service nginx restart
