#!/usr/bin/env bash
# Installs Nginx on web-01

# Update package lists
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Creates index.html that contains "Hello World!"
sudo echo "Hello World" > /var/www/html/index.html

# Reload Nginx
sudo service nginx reload
