#!/usr/bin/env bash
# Script that configures a Nginx server so that /redirect_me is redirecting to another page

# Update package list
sudo apt-get update -y

# Install Nginx
sudo apt install nginx -y

# Return a page that contains the string "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html

echo "server {
	listen 80;
	root /etc/nginx/html;
	index index.html;
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4
	}
}" > /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
