#!/usr/bin/env bash
# Script that configures a Nginx server to have a custom 404 page that contains the string "Ceci n'est pas une page"

# Update package list
sudo apt-get update -y

# Install Nginx
sudo apt install nginx -y

# Return a page that contains the string "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html

# Creates html directory
mkdir -p /etc/nginx/html

# Returns a page that contains the string Ceci n'est pas une page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configures /redirect_me to redirect to another page
# And to have a custom 404 page that contains the string "Ceci n'est pas une page"

echo "server {
	listen 80;
	listen [::]:80 default_server;
	root /var/www/html;
	index  index.html;
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
	error_page 404 /404.html;
	location = /404.html {
		root /etc/nginx/html;
		internal;
	}
}" > /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
