#!/usr/bin/env bash
# Script that configures a Nginx server so that /redirect_me is redirecting to another page

# Install nginx
sudo apt-get update
sudo apt-get -y install nginx

# Returns a page that contains the string Hello World!
echo 'Hello World!' | sudo tee /var/www/html/index.html

# Returns a page that contains the string Ceci n'est pas une page
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

# Configures /redirect_me to redirect to another page
echo "server {
	listen 80;
	listen [::]:80 default_server;
	root   /etc/nginx/html;
	index  index.html;
	location /redirect_me {
		return 301 https://twitter.com/Emmanue17280546;
	}
	error_page 404 /404.html;
	location = /404.html {
		root /etc/nginx/html;
		internal;
	}
}" > /etc/nginx/sites-available/default

# Restarts nginx
sudo service nginx restart
