#!/usr/bin/env bash
# Configures a new Ubuntu machine to add a custom Nginx response header

# Update package lists and install Nginx
sudo apt-get update -y -qq
sudo apt-get install nginx -y

# Allow Nginx on the firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Create index.html that contains "Hello World!"
echo "Hello World!" > /var/www/html/index.htm


# Add custom header to Nginx configuration
HOSTNAME=$(hostname)
sudo sed -i "s/server_name _;/server_name _;\n    add_header X-Served-By \"$HOSTNAME\";/g" /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
