#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend abdullahhr.tech
        bind 0:80
        default_backend web_servers

backend abdullahhr.tech
        balance roundrobin
        server 516976-web-01 54.87.172.28:80
        server 516976-web-02 54.236.45.246:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
