#!/usr/bin/env bash
#Configures an nginx server to listen on port 80 of all the server’s active IPv4 IPs
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
kill "$(pgrep 'nginx' | head -l)"
