#!/usr/bin/env bash
# Script that displays To infinity and beyond indefinitely
# In between each iteration of the loop, adds a sleep 2, I am invincible!!! when receiving a SIGTERM signal

trap 'echo "I am invincible!!!"' 15
while true
do
	echo "To infinity and beyond"
	sleep 2 
done
