#!/usr/bin/env bash
# This script that displays the time for 12 hours and 59 minutes

hour=0
min=0

while [ $hour -le 12 ]
do
	echo Hour: $hour
	while [ $min -lt 60 ]
	do
		echo $min
		((min++))
	done
	min=0
	((hour++))
done
