#!/usr/bin/env bash
# FizzBuzz

for _ in {1..100}
do
	if (( _ % 5 == 0 && _ % 3 == 0 ));
	then
		echo "FizzBuzz"
	elif (( _ % 5 == 0 ));
	then
		echo "Buzz"
	elif (( _ % 3 == 0 ));
	then
		echo "Fizz"
	else
		echo $_
	fi
done
